// 20 real public Instagram reels (each checked to play in Instagram's embed on 2026-10-01), with an
// example idea for each. Used by the demo board (seed-demo.mjs) and `npm run sample-reels`.
// Demo-only fields: `by`, `status`, `assignee`, `votes`, `comments`, `ago` (days since shared) and
// `due` (due date in days from today, negative = overdue).
export const REELS = [
  {
    code: "Dbn-XJhk0_-", by: "leo", ago: 9, status: "in_production", assignee: "leo", due: 2,
    tags: ["bts", "cinematic", "hook"],
    idea: "Behind-the-scenes \"how it's made\" for our product, shot like this: slow camera moves, cold lighting, and a big title-card reveal at the end. Same epic music swell.",
    votes: ["aria", "dev", "mia", "zara"],
    comments: [["mia", "The title-card ending is so good. We could do \"NEW DROP — OCTOBER\" the same way."], ["zara", "I can book the studio Thursday for the slow-mo shots."]],
  },
  {
    code: "DNkpzuaRy-5", by: "mia", ago: 8, status: "approved", assignee: "mia", due: 5,
    tags: ["talking-head", "faq", "series"],
    idea: "Weekly \"You asked, we answered\" series: our founder answers ONE real customer question per reel, straight to camera, with the comment screenshot as the hook.",
    votes: ["aria", "leo"],
    comments: [["aria", "Love it — let's collect 5 questions from DMs first."], ["dev", "I'll pull the top questions from comments this week."]],
  },
  {
    code: "DFIWSVoy1UQ", by: "dev", ago: 12, status: "posted", assignee: "dev", due: -4,
    tags: ["tips", "listicle"],
    idea: "Our own \"5 tips\" reel: numbered on-screen text, a new tip every 2–3 seconds, all about getting more out of our product. Pin it to the profile.",
    votes: ["aria", "mia", "leo", "zara"],
    comments: [["zara", "Posted! 2.1k views on day one 🚀"], ["aria", "Great job — let's make this a monthly thing."]],
  },
  {
    code: "Cj-2mldj4q7", by: "zara", ago: 6, status: "approved", assignee: "zara", due: 0,
    tags: ["hook", "myth-busting", "education"],
    idea: "Myth-busting hook: open with a bold \"___ is a myth\" about our industry, then 3 quick facts as captions. Great for saves and shares.",
    votes: ["aria", "dev", "leo"],
    comments: [["leo", "Which myth first? I vote the \"expensive = better\" one."]],
  },
  {
    code: "CiDmyB4vF7e", by: "leo", ago: 1, status: "new",
    tags: ["product", "lifestyle"],
    idea: "Lifestyle montage: our product in 5 real moments with friends — dinner, game night, road trip… Warm colors, no voice-over, just music.",
    votes: ["mia"],
    comments: [],
  },
  {
    code: "Cj58V9muKyf", by: "mia", ago: 3, status: "new",
    tags: ["storytelling", "pets", "humor"],
    idea: "Mascot story: film the office dog with a \"be more like Odie\" life lesson that ties back to how we treat our customers.",
    votes: ["dev", "zara"],
    comments: [["zara", "Biscuit (my dog) is ready for his close-up 🐶"]],
  },
  {
    code: "Ci-Z9XrgrVx", by: "dev", ago: 5, status: "in_production", assignee: "dev", due: 1,
    tags: ["product", "launch", "screen-recording"],
    idea: "Feature-launch reel for our next update: quick screen-recording cuts, bold \"New and improved!\" captions, end on \"link in bio\".",
    votes: ["aria", "mia"],
    comments: [["aria", "Keep it under 15 seconds please."], ["dev", "Recording the screens now — first cut tomorrow."]],
  },
  {
    code: "CkMLawxAlO8", by: "zara", ago: 2, status: "new",
    tags: ["humor", "relatable", "trend"],
    idea: "Relatable \"everything went wrong but at least…\" skit with a one-line caption punchline. Phone-shot, low effort — perfect Friday post.",
    votes: ["leo", "dev"],
    comments: [],
  },
  {
    code: "CkbzfrZMoqJ", by: "leo", ago: 7, status: "skipped",
    tags: ["asmr"],
    idea: "ASMR close-ups of our product being unboxed and used. Ask \"which sound is better?\" in the caption.",
    votes: [],
    comments: [["aria", "Skipping for now — ASMR doesn't fit our audience. Let's revisit for the holiday unboxing."]],
  },
  {
    code: "C7mxTfOOK9_", by: "mia", ago: 4, status: "approved", assignee: "leo", due: -2,
    tags: ["before-after", "transformation"],
    idea: "Before → after transformation: open on the \"problem\" shot, fast time-lapse of the work, snap cut to the result. Hook text: \"This was intimidating…\"",
    votes: ["aria", "zara", "dev"],
    comments: [["leo", "Need one more day for the after shot, sorry!"]],
  },
  {
    code: "Co-XMYrOaow", by: "zara", ago: 10, status: "new",
    tags: ["engagement", "humor", "comments"],
    idea: "Comment bait: show a weird close-up of our product and ask \"name this\" — then reply to the funniest comments with follow-up reels.",
    votes: ["dev"],
    comments: [["mia", "This got 270+ comments for KFC 😂 cheap to make, let's try it."]],
  },
  {
    code: "CslvWL0IJul", by: "aria", ago: 11, status: "posted", assignee: "mia", due: -6,
    tags: ["skit", "relatable"],
    idea: "\"POV: quick call\" work-from-home skit about our customers' biggest pain point. Two people, one desk, POV caption.",
    votes: ["leo", "zara"],
    comments: [["mia", "Posted ✅ — the \"POV:\" caption did really well."]],
  },
  {
    code: "C6PSYrnO8Oz", by: "mia", ago: 6, status: "approved", assignee: "zara", due: 7,
    tags: ["street-interview", "engagement"],
    idea: "Street interviews at our next event: ask people for their red flags and green flags about our category, then ask viewers to drop theirs in the comments.",
    votes: ["aria", "leo", "dev"],
    comments: [["aria", "Let's film this at the pop-up on the 8th."]],
  },
  {
    code: "C85EQ9QNdFU", by: "dev", ago: 3, status: "in_production", assignee: "mia", due: 3,
    tags: ["humor", "brand-voice", "trend"],
    idea: "Use the \"-1000 aura points\" trend in our brand voice: reply-to-comment format, (gently) roasting a silly customer question.",
    votes: ["aria", "zara", "leo", "mia"],
    comments: [["zara", "Their tone is perfect for this — we just need the right question."], ["mia", "Drafting 3 scripts, will share them here."]],
  },
  {
    code: "DB907TsSMdh", by: "zara", ago: 1, status: "new",
    tags: ["comparison", "product", "results"],
    idea: "Side-by-side comparison: use our product on one half only, then reveal both halves. Simple split screen, no talking.",
    votes: ["aria"],
    comments: [],
  },
  {
    code: "Ca2qkO8AImL", by: "aria", ago: 12, status: "posted", assignee: "zara", due: -8,
    tags: ["seasonal", "community"],
    idea: "Calendar moment: celebrate the people behind our product (team + customers) on the next big day — quick portraits with name cards.",
    votes: ["dev", "mia"],
    comments: [["zara", "Posted 💐 — saving this format for Teacher's Day too."]],
  },
  {
    code: "DArZzNiu4d7", by: "leo", ago: 2, status: "approved", assignee: "dev", due: 4,
    tags: ["collab", "trend", "reply"],
    idea: "React to a viral moment related to us (like Woobles did with the aquarium's Pesto) — make our own version within 48 hours while it's hot.",
    votes: ["mia", "zara"],
    comments: [["dev", "We need a \"trend watch\" habit so we're faster on these."]],
  },
  {
    code: "Cb1lXoFFkvq", by: "mia", ago: 5, status: "in_production", assignee: "zara", due: -1,
    tags: ["ugc", "creators", "results"],
    idea: "Creator results reel: send our product to 3 micro-creators, ask for a \"6 weeks of using…\" before/after, and repost as a collab post.",
    votes: ["aria", "leo"],
    comments: [["zara", "2 of 3 creators sent their clips — waiting on the last one."]],
  },
  {
    code: "DCAg4bly5Sm", by: "dev", ago: 0.3, status: "new",
    tags: ["pop-culture", "launch"],
    idea: "Pop-culture tie-in: theme a mini bundle around a big movie release and \"dance through\" the reveal like this.",
    votes: [],
    comments: [],
  },
  {
    code: "C9LIGZdSfRm", by: "zara", ago: 0.1, status: "new",
    tags: ["hook", "question", "tutorial"],
    idea: "Question hook — \"Is it really possible to ___ with just ___?\" — then a 3-step demo that proves it. Works for all our how-to content.",
    votes: ["leo"],
    comments: [],
  },
];
